name: Trigger auto deployment for container-app-3bl7g6s6jk5mk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3bl7g6s6jk5mk-AutoDeployTrigger-8fc97c04-030d-4774-be3f-c430f2f10331.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3BL7G6S6JK5MK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3BL7G6S6JK5MK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3BL7G6S6JK5MK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3BL7G6S6JK5MK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3BL7G6S6JK5MK_REGISTRY_PASSWORD }}
          containerAppName: container-app-3bl7g6s6jk5mk
          resourceGroup: todonodejspgsqlgoogleauth9e61801f
          imageToBuild: default/container-app-3bl7g6s6jk5mk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


